# Example: Add Home Assistant MCP to your existing docker-compose.yml
# Copy the 'ha-mcp' service below and add it to your services section

services:
  # If you already have Home Assistant running, you can reference it:
  # homeassistant:
  #   image: homeassistant/home-assistant:stable
  #   ... your existing HA config ...

  # Add this service to your existing docker-compose.yml:
  ha-mcp:
    build:
      context: .
      dockerfile: Dockerfile
    image: homeassistant-ai/ha-mcp:latest
    container_name: ha-mcp-server
    environment:
      # Point to your Home Assistant instance
      # If HA is in same compose file, use service name: http://homeassistant:8123
      # If HA is external, use: http://your-ha-ip:8123
      - HOME_ASSISTANT_URL=http://homeassistant:8123
      # Set your Home Assistant long-lived access token
      - HOMEASSISTANT_TOKEN=${HA_TOKEN}
      # Optional: Configure backup hint behavior
      - BACKUP_HINT=normal
    restart: unless-stopped
    # If using same compose file as HA, add to HA's network:
    # networks:
    #   - your-ha-network

# Usage:
# 1. Create .env file: HA_TOKEN=your_long_lived_access_token
# 2. Add ha-mcp service to your docker-compose.yml
# 3. Run: docker-compose up -d ha-mcp
# 4. Connect your MCP client to the ha-mcp container
#
# Get a Home Assistant token:
# Profile → Long-Lived Access Tokens → Create Token
