name: Launch Codex async worker
description: Start a Codex cloud worker to investigate the failing workflow asynchronously.
inputs:
  prompt:
    description: Fully composed prompt to feed into the Codex cloud worker.
    required: true
runs:
  using: composite
  steps:
    - shell: bash
      env:
        PROMPT_TEXT: ${{ inputs.prompt }}
      run: |
        set -euo pipefail
        printf '%s\n' "${PROMPT_TEXT}" | \
          codex cloud exec --env 68f2eebb94d48191ba53625a2b09ae54 -
