// Auto-activate tab from ?tab=<name> query string (used by approval URLs
// generated by the policy middleware: /settings?tab=tool-security-policies&token=...).
// If a &token=X is present and the target is the policy tab, scroll to
// the matching pending entry once policyLoadPending() resolves.
(function activateTabFromQuery() {
  try {
    const params = new URLSearchParams(window.location.search);
    const target = params.get('tab');
    if (!target) return;
    const tabBtn = document.querySelector('.tab[data-panel="' + target + '"]');
    if (!tabBtn) return;
    activateTab(target);
    const token = params.get('token');
    if (token && target === 'tool-security-policies') {
      // policyLoadPending() runs inside activateTab; wait a tick then
      // scroll to the matching pending entry if it exists.
      setTimeout(() => {
        const row = document.querySelector('[data-pending-token="' + token + '"]');
        if (row && row.scrollIntoView) {
          row.scrollIntoView({behavior: 'smooth', block: 'center'});
        }
      }, 500);
    }
  } catch (_) { /* best-effort */ }
})();

// #1572 accessibility prefs — bidirectional binding between the header
// theme toggle, the Accessibility tab controls, and the underlying
// localStorage / <html> attributes. The anti-FOUC head script already set
// the initial attributes; this module keeps them in sync for the rest of
// the session and persists user changes. The block from `const PREFS` to
// `const APPLY` must stay logically identical to the copy in
// site/src/layouts/Layout.astro (comments and formatting may differ) —
// enforced by tests/src/unit/test_anti_fouc_parity.py.
(function bindAccessibilityPrefs() {
  const root = document.documentElement;
  const mql = window.matchMedia('(prefers-color-scheme: light)');
  const PREFS = {
    theme:    { key: 'ha-mcp-theme',         default: 'auto'      },
    fontSize: { key: 'ha-mcp-font-size',     default: '100'       },
    contrast: { key: 'ha-mcp-contrast',      default: 'normal'    },
    shade:    { key: 'ha-mcp-shade',         default: 'off-white' },
    custom:   { key: 'ha-mcp-custom-colors', default: ''          },
  };
  // One-click presets (Firefox Reader View shape, #1574 review): each sets
  // the full (theme, shade, contrast) triple; the checked chip is derived
  // back from the stored triple, so hand-edited combos simply match none.
  const PRESETS = {
    dark:     { theme: 'dark',  shade: 'off-white', contrast: 'normal' },
    light:    { theme: 'light', shade: 'off-white', contrast: 'normal' },
    auto:     { theme: 'auto',  shade: 'off-white', contrast: 'normal' },
    paper:    { theme: 'light', shade: 'paper',     contrast: 'normal' },
    gray:     { theme: 'light', shade: 'gray',      contrast: 'normal' },
    contrast: { theme: 'light', shade: 'pure',      contrast: 'high'   },
  };
  const read = (p) => {
    try { return localStorage.getItem(PREFS[p].key) || PREFS[p].default; }
    catch (_) { return PREFS[p].default; }
  };
  const write = (p, v) => {
    let stored = true;
    try { localStorage.setItem(PREFS[p].key, v); } catch (_) { stored = false; }
    // Surface-specific follow-up (server sync on the settings UI,
    // blocked-storage note on both) lives outside this mirrored core.
    if (window.__haMcpPrefsHook) window.__haMcpPrefsHook(p, v, stored);
  };

  // Apply functions mirror what the anti-FOUC head script does, so the
  // runtime path and the pre-paint path stay observably identical.
  const applyTheme = (pref) => {
    const resolved = pref === 'auto' ? (mql.matches ? 'light' : 'dark') : pref;
    root.setAttribute('data-theme', resolved);
  };
  const applyFontSize = (pct) => {
    const n = parseInt(pct, 10);
    if (isNaN(n) || n <= 100 || n > 150) root.style.fontSize = '';
    else root.style.fontSize = (16 * n / 100) + 'px';
  };
  const applyContrast = (tier) => {
    if (tier === 'high') root.setAttribute('data-contrast', 'high');
    else root.removeAttribute('data-contrast');
  };
  const applyShade = (shade) => {
    if (shade && shade !== 'off-white') root.setAttribute('data-shade', shade);
    else root.removeAttribute('data-shade');
  };
  const HEX_RE = /^#[0-9a-fA-F]{6}$/;
  const channels = (hex) =>
    parseInt(hex.slice(1, 3), 16) + ' ' + parseInt(hex.slice(3, 5), 16) + ' ' + parseInt(hex.slice(5, 7), 16);
  // Custom colors layer on top of any preset as inline styles (inline beats
  // stylesheet rules, so the cascade is: preset CSS -> user custom). Both
  // surfaces' variable names are written; names a surface does not use are
  // inert. Returns the parsed object so callers can reuse it.
  const CUSTOM_VARS = {
    bg:     { hex: ['--bg'], chan: ['--surface-0'] },
    text:   { hex: ['--text', '--text-primary'], chan: [] },
    accent: { hex: ['--accent', '--accent-text'], chan: ['--brand'] },
  };
  const applyCustom = (raw) => {
    for (const part in CUSTOM_VARS) {
      CUSTOM_VARS[part].hex.concat(CUSTOM_VARS[part].chan).forEach((name) => root.style.removeProperty(name));
    }
    let custom = {};
    try { custom = JSON.parse(raw || '{}') || {}; } catch (_) { return {}; }
    for (const part in CUSTOM_VARS) {
      const v = custom[part];
      if (typeof v !== 'string' || !HEX_RE.test(v)) continue;
      CUSTOM_VARS[part].hex.forEach((name) => root.style.setProperty(name, v));
      CUSTOM_VARS[part].chan.forEach((name) => root.style.setProperty(name, channels(v)));
    }
    return custom;
  };
  const APPLY = { theme: applyTheme, fontSize: applyFontSize, contrast: applyContrast, shade: applyShade, custom: applyCustom };

  // #1574 review: localStorage is the synchronous store the anti-FOUC
  // script reads at paint time, but it is origin-scoped and the stdio
  // sidecar's port (= the origin) can still change: stable by default
  // since #2131, yet fresh on first spawn, a lost ui.state, a pin
  // change, or a taken remembered port. This hook therefore (a) mirrors
  // every change to the server
  // (./api/settings/theme -> theme_prefs.json), which seeds the next
  // fresh origin via the server-prefs head script, and (b) surfaces a
  // blocked localStorage (private mode) once instead of silently losing
  // the choices on reload. Debounced so color-picker drags don't flood
  // the endpoint; best-effort because the browser copy already applied.
  const storageNote = document.getElementById('a11y-storage-note');
  const pendingPrefs = {};
  let prefsSyncTimer = null;
  window.__haMcpPrefsHook = (pref, value, stored) => {
    if (!stored && storageNote) storageNote.hidden = false;
    pendingPrefs[pref] = value;
    clearTimeout(prefsSyncTimer);
    prefsSyncTimer = setTimeout(() => {
      const body = JSON.stringify(pendingPrefs);
      for (const k in pendingPrefs) delete pendingPrefs[k];
      fetch('./api/settings/theme', {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body,
      }).then((resp) => {
        // A non-2xx means client and server disagree about valid values —
        // an implementation bug worth a console trail, not a user error.
        if (!resp.ok) console.warn('ha-mcp: theme prefs not persisted:', resp.status);
      }).catch(() => { /* offline / sidecar gone — localStorage still has it */ });
    }, 400);
  };

  const setPref = (pref, value) => {
    write(pref, value);
    APPLY[pref](value);
  };
  const applyPreset = (name) => {
    const p = PRESETS[name];
    if (!p) return;
    setPref('theme', p.theme);
    setPref('shade', p.shade);
    setPref('contrast', p.contrast);
  };
  const reflectPreset = () => {
    const theme = read('theme'), shade = read('shade'), contrast = read('contrast');
    let active = '';
    for (const name in PRESETS) {
      const p = PRESETS[name];
      if (p.theme === theme && p.shade === shade && p.contrast === contrast) { active = name; break; }
    }
    document.querySelectorAll('input[type="radio"][name="a11y-preset"]').forEach((r) => {
      r.checked = (r.value === active);
    });
  };
  const reflectRadio = (name, value) => {
    document.querySelectorAll('input[type="radio"][name="' + name + '"]').forEach((r) => {
      r.checked = (r.value === value);
    });
  };
  // WCAG 2.x relative-luminance contrast for the custom-color warning.
  const luminance = (hex) => {
    const f = (i) => {
      const c = parseInt(hex.slice(i, i + 2), 16) / 255;
      return c <= 0.03928 ? c / 12.92 : Math.pow((c + 0.055) / 1.055, 2.4);
    };
    return 0.2126 * f(1) + 0.7152 * f(3) + 0.0722 * f(5);
  };
  const updateContrastWarning = (custom) => {
    const warn = document.getElementById('a11y-contrast-warning');
    if (!warn) return;
    const comparable = HEX_RE.test(custom.bg || '') && HEX_RE.test(custom.text || '');
    if (!comparable) { warn.hidden = true; return; }
    const l1 = luminance(custom.bg), l2 = luminance(custom.text);
    warn.hidden = (Math.max(l1, l2) + 0.05) / (Math.min(l1, l2) + 0.05) >= 4.5;
  };

  // Header <select> for theme — quick Dark/Light/Auto access.
  const headerToggle = document.getElementById('themeToggle');
  if (headerToggle) {
    headerToggle.value = read('theme');
    headerToggle.addEventListener('change', () => {
      setPref('theme', headerToggle.value);
      reflectPreset();
      refreshSwatches();
    });
  }

  // Re-apply when the OS preference flips while in Auto.
  mql.addEventListener('change', () => {
    if (read('theme') === 'auto') {
      applyTheme('auto');
      refreshSwatches();
    }
  });

  reflectRadio('a11y-font-size', read('fontSize'));
  reflectPreset();
  // Initialize each swatch from the saved custom value, falling back to
  // the theme's current computed color so the wells show reality instead
  // of an arbitrary black default.
  const cssColorToHex = (value) => {
    const v = (value || '').trim();
    if (HEX_RE.test(v)) return v;
    let m = v.match(/^rgba?\((\d+)[, ]+(\d+)[, ]+(\d+)/);
    if (!m) m = v.match(/^(\d+) (\d+) (\d+)$/);
    if (!m) return '';
    return '#' + [m[1], m[2], m[3]].map((n) => (+n).toString(16).padStart(2, '0')).join('');
  };
  const currentColorFor = (part) => {
    const body = getComputedStyle(document.body);
    const rootStyle = getComputedStyle(root);
    if (part === 'bg') return cssColorToHex(body.backgroundColor);
    if (part === 'text') return cssColorToHex(body.color);
    return cssColorToHex(rootStyle.getPropertyValue('--accent')) ||
      cssColorToHex(rootStyle.getPropertyValue('--brand'));
  };
  const customInputs = document.querySelectorAll('input[type="color"][data-custom]');
  // Sync the swatch wells with reality: a stored custom value wins,
  // otherwise the active theme's computed color. Re-run after anything
  // that changes the active palette (preset click, header toggle, OS
  // auto-flip, clear, reset) so the wells never keep showing a previous
  // theme's colors.
  const refreshSwatches = () => {
    let custom = {};
    try { custom = JSON.parse(read('custom') || '{}') || {}; } catch (_) { /* ignore */ }
    customInputs.forEach((inp) => {
      const v = custom[inp.dataset.custom];
      const fallback = currentColorFor(inp.dataset.custom);
      if (HEX_RE.test(v || '')) inp.value = v;
      else if (fallback) inp.value = fallback;
    });
  };
  updateContrastWarning(applyCustom(read('custom')));
  refreshSwatches();
  customInputs.forEach((inp) => {
    inp.addEventListener('input', () => {
      let custom = {};
      try { custom = JSON.parse(read('custom') || '{}') || {}; } catch (_) { /* start fresh */ }
      custom[inp.dataset.custom] = inp.value;
      write('custom', JSON.stringify(custom));
      applyCustom(read('custom'));
      updateContrastWarning(custom);
    });
  });
  const clearBtn = document.getElementById('a11y-custom-clear');
  if (clearBtn) {
    clearBtn.addEventListener('click', () => {
      write('custom', '');
      updateContrastWarning(applyCustom(''));
      refreshSwatches();
    });
  }

  // Scope the change listener to the Accessibility panel rather than the
  // document: the settings page carries dozens of unrelated inputs (tool
  // toggles, server fields, backup forms) and a document-level listener
  // would fire on every one of them just to bail the filter.
  const a11yPanel = document.getElementById('panel-accessibility');
  if (a11yPanel) {
    a11yPanel.addEventListener('change', (e) => {
      const t = e.target;
      if (!(t instanceof HTMLInputElement) || t.type !== 'radio') return;
      if (t.name === 'a11y-preset') {
        applyPreset(t.value);
        if (headerToggle) headerToggle.value = read('theme');
        refreshSwatches();
      } else if (t.name === 'a11y-font-size') {
        setPref('fontSize', t.value);
      }
    });
  }

  const resetBtn = document.getElementById('a11y-reset');
  if (resetBtn) {
    resetBtn.addEventListener('click', () => {
      setPref('theme', PREFS.theme.default);
      setPref('shade', PREFS.shade.default);
      setPref('contrast', PREFS.contrast.default);
      setPref('fontSize', PREFS.fontSize.default);
      write('custom', '');
      updateContrastWarning(applyCustom(''));
      reflectRadio('a11y-font-size', PREFS.fontSize.default);
      reflectPreset();
      if (headerToggle) headerToggle.value = PREFS.theme.default;
      refreshSwatches();
    });
  }
})();

// --- Entity visibility filter tab (#1728) ---
let visibilityVersion = 1;

function _visibilityShowLoadError(msg) {
  const el = document.getElementById('visibility-load-error');
  if (!el) return;
  el.style.display = msg ? '' : 'none';
  el.textContent = msg || '';
}

function _visibilityParseList(value, sep) {
  return value.split(sep).map(s => s.trim()).filter(Boolean);
}

async function visibilityLoadConfig() {
  _visibilityShowLoadError('');
  let resp;
  try {
    resp = await fetch('./api/visibility/config');
  } catch (e) {
    _visibilityShowLoadError(t('visibility.errors.reach_server', {message: e.message}, 'Could not reach the server: ' + e.message));
    return;
  }
  if (!resp.ok) {
    let detail = 'HTTP ' + resp.status;
    try {
      const body = await resp.json();
      if (body && body.error) detail = body.error;
      if (body && body.visibility_file_corrupt) {
        detail += t(
          'visibility.errors.corrupt_suffix',
          {},
          ' (entity_visibility.json appears corrupt; edit or delete it on the App (add-on) /data volume)'
        );
      }
    } catch (_e) { /* keep the HTTP-status fallback */ }
    _visibilityShowLoadError(t('visibility.errors.load_detail', {detail}, 'Failed to load visibility config: ' + detail));
    return;
  }
  const c = await resp.json();
  visibilityVersion = c.version ?? 1;
  const cats = c.exclude_categories || [];
  document.getElementById('visibility-enabled').checked = !!c.enabled;
  document.getElementById('visibility-enforce').checked = !!c.enforce;
  document.getElementById('visibility-restrict-report-issue').checked = !!c.restrict_report_issue;
  document.getElementById('visibility-cat-diagnostic').checked = cats.includes('diagnostic');
  document.getElementById('visibility-cat-config').checked = cats.includes('config');
  document.getElementById('visibility-exclude-hidden').checked = !!c.exclude_hidden;
  document.getElementById('visibility-areas').value = (c.exclude_areas || []).join(', ');
  document.getElementById('visibility-labels').value = (c.exclude_labels || []).join(', ');
  document.getElementById('visibility-deny').value = (c.deny_entity_ids || []).join('\n');
  document.getElementById('visibility-allow-areas').value = (c.allow_areas || []).join(', ');
  document.getElementById('visibility-allow-labels').value = (c.allow_labels || []).join(', ');
  document.getElementById('visibility-allow-entities').value = (c.allow_entity_ids || []).join('\n');
  document.getElementById('visibility-respect-assist').checked = !!c.respect_assist_exposure;
}

async function visibilitySaveConfig() {
  const statusEl = document.getElementById('visibility-save-status');
  const cats = [];
  if (document.getElementById('visibility-cat-diagnostic').checked) cats.push('diagnostic');
  if (document.getElementById('visibility-cat-config').checked) cats.push('config');
  const config = {
    version: visibilityVersion,
    enabled: document.getElementById('visibility-enabled').checked,
    enforce: document.getElementById('visibility-enforce').checked,
    restrict_report_issue: document.getElementById('visibility-restrict-report-issue').checked,
    exclude_categories: cats,
    exclude_hidden: document.getElementById('visibility-exclude-hidden').checked,
    deny_entity_ids: _visibilityParseList(document.getElementById('visibility-deny').value, '\n'),
    exclude_areas: _visibilityParseList(document.getElementById('visibility-areas').value, ','),
    exclude_labels: _visibilityParseList(document.getElementById('visibility-labels').value, ','),
    allow_areas: _visibilityParseList(document.getElementById('visibility-allow-areas').value, ','),
    allow_labels: _visibilityParseList(document.getElementById('visibility-allow-labels').value, ','),
    allow_entity_ids: _visibilityParseList(document.getElementById('visibility-allow-entities').value, '\n'),
    respect_assist_exposure: document.getElementById('visibility-respect-assist').checked,
  };
  setStatusAlert(statusEl, false);
  statusEl.textContent = t('status.saving', {}, 'Saving...');
  let resp;
  try {
    resp = await fetch('./api/visibility/config', {
      method: 'PUT',
      headers: { 'Content-Type': 'application/json' },
      body: JSON.stringify(config),
    });
  } catch (e) {
    setStatusAlert(statusEl, true);
    statusEl.textContent = t('errors.save_failed_detail', {message: e.message}, 'Save failed: ' + e.message);
    return;
  }
  if (resp.status === 409) {
    // Do NOT reload the config here: that would overwrite the user's unsaved
    // edits (there would be nothing left to "re-apply"). Keep the edits in the
    // form, surface the conflict, and let the user reload deliberately — mirrors
    // the policy tab's optimistic-lock message.
    setStatusAlert(statusEl, true);
    statusEl.textContent = t(
      'visibility.errors.conflict',
      {},
      'Config was changed in another tab or session. Reload the page to see the latest, then re-apply your changes.'
    );
    return;
  }
  if (!resp.ok) {
    let detail = 'HTTP ' + resp.status;
    try { const b = await resp.json(); if (b && b.error) detail = b.error; } catch (_e) { /* fallback */ }
    setStatusAlert(statusEl, true);
    statusEl.textContent = t('errors.save_failed_detail', {message: detail}, 'Save failed: ' + detail);
    return;
  }
  const body = await resp.json();
  visibilityVersion = body.version ?? (visibilityVersion + 1);
  setStatusAlert(statusEl, false);
  statusEl.textContent = t('status.saved', {}, 'Saved.');
}

(function wireVisibilitySave() {
  const btn = document.getElementById('visibility-save-btn');
  if (btn) btn.addEventListener('click', visibilitySaveConfig);
})();
