# Build configuration for Home Assistant add-on
# Defines base images for different architectures

build_from:
  aarch64: "ghcr.io/astral-sh/uv:0.9.0-python3.11-alpine3.20"
  amd64: "ghcr.io/astral-sh/uv:0.9.0-python3.11-alpine3.20"
  armhf: "ghcr.io/astral-sh/uv:0.9.0-python3.11-alpine3.20"
  armv7: "ghcr.io/astral-sh/uv:0.9.0-python3.11-alpine3.20"
  i386: "ghcr.io/astral-sh/uv:0.9.0-python3.11-alpine3.20"
