name: "Home Assistant MCP Server"
description: "AI assistant integration for Home Assistant via Model Context Protocol (MCP)"
version: "2.3.1"
slug: "ha-mcp"
url: "https://github.com/homeassistant-ai/ha-mcp"
arch:
  - aarch64  # 64-bit ARM (Raspberry Pi 4+, modern ARM devices)
  - amd64    # 64-bit x86 (most PCs and servers)
  # Note: 32-bit platforms (armhf, armv7, i386) not supported
  # uv base image only provides amd64 and arm64 builds
init: false
startup: application
boot: manual
# Enable access to Supervisor API for auto-discovery
hassio_api: true
hassio_role: default
# Enable access to Home Assistant API
homeassistant_api: true
# Options for user configuration
options:
  backup_hint: "normal"
schema:
  backup_hint: list(strong|normal|weak|auto)
# Add-on will run on stdio for MCP communication
stdin: true
