name: "Home Assistant MCP Server"
description: "AI assistant integration for Home Assistant via Model Context Protocol (MCP)"
version: "3.1.0"
slug: "ha_mcp"
url: "https://github.com/homeassistant-ai/ha-mcp"
arch:
  - aarch64  # 64-bit ARM (Raspberry Pi 4+, modern ARM devices)
  - amd64    # 64-bit x86 (most PCs and servers)
  # Note: 32-bit platforms (armhf, armv7, i386) not supported
  # uv base image only provides amd64 and arm64 builds
init: false
startup: application
boot: manual
# Enable access to Supervisor API for auto-discovery
hassio_api: true
hassio_role: default
# Enable access to Home Assistant API
homeassistant_api: true
# Enable host network mode for local network access
host_network: true
# Use pre-built Docker images
image: "ghcr.io/homeassistant-ai/ha-mcp-addon-{arch}"
# Options for user configuration
options:
  backup_hint: "normal"
  secret_path: ""
schema:
  backup_hint:
    required: false
    advanced: true
    default: "normal"
    description: "Controls when backups are suggested before operations."
    options:
      - "strong"
      - "normal"
      - "weak"
      - "auto"
  secret_path:
    required: false
    advanced: true
    description: "Custom secret path (overrides auto-generated). Leave empty for auto-generation."
# Add-on exposes HTTP port for MCP communication (fixed internal port)
ports:
  9583/tcp: 9583
